import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CircularProgress from "@mui/material/CircularProgress";
import { Button, Box } from "@mui/material";
import { useState } from "react";
import {useRouter} from 'next/router';


export default function Home() {
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const handleLogin = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      router.push('/dashboard');
    }, 2000);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="container">
        <div className="form">
          <div className="input-field">
            <label for="email">Email</label>
            <input
              type="email"
              placeholder="example@example.com"
              id="email"
              name="email"
            />
          </div>
          <div className="input-field">
            <label for="password">Password</label>
            <input
              type="password"
              placeholder="********"
              id="password"
              name="password"
            />
          </div>
          <div className="input-field">
            <label for="remember">
              <input type="checkbox" name="" id="remember" />
              Remember me
            </label>
          </div>
          <div className="action">
            <Box sx={{ m: 1, position: "relative" }}>
              <button
                className="btn"
                variant="contained"
                disabled={loading}
                onClick={handleLogin}
              >
                Login
              </button>
              {loading && (
                <CircularProgress
                  size={24}
                  sx={{
                    position: "absolute",
                    top: "50%",
                    left: "50%",
                    marginTop: "-12px",
                    marginLeft: "-12px",
                  }}
                />
              )}
            </Box>
            {/* <Button
              variant="contained"
              disabled={loading}
              onClick={handleLogin}
              id="btn"
              className="btn"
            >
              {loading && <CircularProgress size={22} disableShrink />}
            </Button> */}
          </div>
        </div>
      </div>
      </main>

      <footer className={styles.footer}>
        <span style={{ display: "flex", gap: ".5rem" }}>
          Develop by <a href="https://github.com/hanibalgirmay">Hanibal G.</a>
        </span>
      </footer>
    </div>
  );
}
